version: '3.2'
services:

  smtp-relay:
    image: turgon37/smtp-relay:latest
    hostname: smtp1
    domainname: 8sec.local
    dns_search: 8sec.local
    environment:
      TZ: Asia/Hong_Kong
      RELAY_MYHOSTNAME: smtp1.8sec.local
      RELAY_MYDOMAIN: 8sec.local
      RELAY_MYNETWORKS: '10.122.80.0/24'
      RELAY_HOST: '[email-smtp.ap-southeast-1.amazonaws.com]:587'
      POSTCONF_compatibility_level: '2'
    ports:
      - 25:25/tcp

  maildev:
    image: maildev/maildev:latest
    networks:
      default:
        aliases:
          - maildev.local
    ports:
      - 8010:80
